# Generated by Django 4.0 on 2021-12-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyUser',
        ),
    ]
