# Generated by Django 4.0 on 2021-12-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('room', '0002_delete_spotifyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('lastActive', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=50)),
                ('host', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
    ]
