# Generated by Django 4.0 on 2021-12-21 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
