# Generated by Django 4.0 on 2021-12-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='queue',
            field=models.JSONField(null=True),
        ),
    ]
