# Generated by Django 4.0 on 2021-12-25 03:41

from django.db import migrations, models
import room.models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_room_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lastSearch',
            field=models.JSONField(default=room.models.Room.defaultSearch),
        ),
    ]
