# Generated by Django 4.0 on 2021-12-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_room_lastsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='prevTrack',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='room',
            name='queue',
            field=models.JSONField(default=list),
        ),
    ]
