# Generated by Django 4.0 on 2021-12-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyuser',
            old_name='auth_token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='expires_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='expires_in',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='scope',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='token_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
